---
collections:
  - name: example.mycollection
    version: 0.0.0
    type: dir
    source: ./mycollection
    # source: https://example.com/my/repo.git

# roles:
#   - src: git+file://home/yamause/Dev/role_test/mycollection
