---
collections:

  # Source GitHub
  #   - name: yamause.test
  #     version: 0.0.0
  #     type: git
  #     source: https://github.com/yamause/test-ansible-collection.git

  # Source local directory
  - name: yamause.test
    version: 0.0.0
    type: dir
    source: .
