---
- name: Test custom module
  hosts: localhost
  tasks:
    - name: Use custom module to output a value
      yamause.test.say_yamause:
        input_value: "Hello, Ansible!"
      register: result

    - name: Print the result
      ansible.builtin.debug:
        var: result
